
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git osx zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

PATH=/usr/local/bin:"$PATH"

prompt_dir() {
    prompt_segment blue black "${PWD##*/}"
}

prompt_context() {
  local user=`whoami`

  if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment green default "%(!.%{%F{yellow}%}.)"
  fi
}

export WORKON_HOME=~/.envs
source /usr/local/bin/virtualenvwrapper.sh

alias nosetests='nosetests -s --nologcapture'
alias vi='nvim'
alias vim='nvim'
alias mkvenv='mkvirtualenv -p /usr/local/bin/python2'
alias mkvenv3='mkvirtualenv -p /usr/local/bin/python3'
alias rmvenv='rmvirtualenv'
alias da='deactivate'
alias wk='workon ${PWD##*/}'
alias dc='docker-compose'
alias dm='docker-machine'
alias ipy='ipython'

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
