
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git osx autojump zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

PATH=/usr/local/bin:"$PATH"

prompt_dir() {
    prompt_segment green black "${PWD##*/}"
}

prompt_context() {
  local user=`whoami`

  if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)✝"
  fi
}

export WORKON_HOME=~/.envs
source /usr/local/bin/virtualenvwrapper.sh

alias nosetests='nosetests -s --nologcapture'
alias vi='nvim'
alias vim='nvim'
alias mkvenv='mkvirtualenv'
alias mkvenv3='mkvirtualenv -p /usr/local/bin/python3'
alias rmvenv='rmvirtualenv'
alias da='deactivate'
alias wkn='workon ${PWD##*/}'
alias dc='docker-compose'
alias dm='docker-machine'

export AIRBRIDGE_DEVELOP_QUEUE=udl-stat-develop-insert-queue-yunseop
export USE_AIRBRIDGE_LOCAL_DB=true

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
