
export ZSH=/Users/sys/.oh-my-zsh

ZSH_THEME="agnoster"

plugins=(git)

source $ZSH/oh-my-zsh.sh

PATH=/usr/local/bin:"$PATH"

# export WORKON_HOME=~/.envs
# source /usr/local/bin/virtualenvwrapper.sh

prompt_dir() { 
    prompt_segment blue black "${PWD##*/}"
}

prompt_context() {
  local user=`whoami`

  if [[ "$user" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)✝"
  fi
}

alias nosetests='nosetests -s --nologcapture'
alias vi='nvim'
alias vim='nvim'

export AIRBRIDGE_DEVELOP_QUEUE=udl-stat-develop-insert-queue-yunseop
export USE_AIRBRIDGE_LOCAL_DB=true

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
